[2020-04-17 23:58:27,731]{/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /rent/1 [GET]
Traceback (most recent call last):
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/fullstack5_andre_novado/Restful-API/Flask_routing/blueprints/rent/resources.py", line 27, in get
    return marshal(qry, Rents.response_field), 200
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 636, in marshal
    return OrderedDict([(envelope, OrderedDict(items))]) if envelope else OrderedDict(items)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 635, in <genexpr>
    for k, v in fields.items())
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 636, in marshal
    return OrderedDict([(envelope, OrderedDict(items))]) if envelope else OrderedDict(items)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 635, in <genexpr>
    for k, v in fields.items())
AttributeError: 'NoneType' object has no attribute 'output'
[2020-04-17 23:58:27,735]{/home/andrenovado/Documents/Coding/Alterra/fullstack5_andre_novado/Restful-API/Flask_routing/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/rent/1?", "request": {"user_id": 8, "book_id": 6}, "response": {"message": "Internal Server Error"}}
[2020-04-17 23:58:57,909]{/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /rent/1 [POST]
Traceback (most recent call last):
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: post() got an unexpected keyword argument 'id'
[2020-04-17 23:58:57,910]{/home/andrenovado/Documents/Coding/Alterra/fullstack5_andre_novado/Restful-API/Flask_routing/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/rent/1?", "request": {"user_id": 1, "book_id": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-18 00:00:05,627]{/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /rent/1 [POST]
Traceback (most recent call last):
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: post() got an unexpected keyword argument 'id'
[2020-04-18 00:00:05,629]{/home/andrenovado/Documents/Coding/Alterra/fullstack5_andre_novado/Restful-API/Flask_routing/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/rent/1?", "request": {"user_id": 1, "book_id": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-18 00:00:10,501]{/home/andrenovado/Documents/Coding/Alterra/fullstack5_andre_novado/Restful-API/Flask_routing/blueprints/__init__.py:60} WARNING - REQUEST_LOG	{"method": "POST", "code": "200 OK", "uri": "/rent?", "request": {"user_id": 1, "book_id": 1}, "response": {"id": 2, "book_id": 1, "user_id": "1", "return_date": "Sat, 18 Apr 2020 00:00:10 -0000", "created_at": "Sat, 18 Apr 2020 00:00:10 -0000", "updated_at": null, "deleted_at": null}}
[2020-04-18 00:00:36,194]{/home/andrenovado/Documents/Coding/Alterra/fullstack5_andre_novado/Restful-API/Flask_routing/blueprints/__init__.py:60} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/rent/1?", "request": {"user_id": 1, "book_id": 1}, "response": {"id": 1, "book_id": 6, "user_id": "8", "return_date": "Fri, 17 Apr 2020 23:27:39 -0000", "created_at": "Fri, 17 Apr 2020 23:27:39 -0000", "updated_at": null, "deleted_at": null}}
[2020-04-18 00:02:06,014]{/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /rent/1 [GET]
Traceback (most recent call last):
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/fullstack5_andre_novado/Restful-API/Flask_routing/blueprints/rent/resources.py", line 27, in get
    return marshal(qry, Rents.response_field), 200
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 636, in marshal
    return OrderedDict([(envelope, OrderedDict(items))]) if envelope else OrderedDict(items)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 635, in <genexpr>
    for k, v in fields.items())
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 636, in marshal
    return OrderedDict([(envelope, OrderedDict(items))]) if envelope else OrderedDict(items)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 635, in <genexpr>
    for k, v in fields.items())
AttributeError: 'NoneType' object has no attribute 'output'
[2020-04-18 00:02:06,017]{/home/andrenovado/Documents/Coding/Alterra/fullstack5_andre_novado/Restful-API/Flask_routing/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/rent/1?", "request": {"user_id": 1, "book_id": 1}, "response": {"message": "Internal Server Error"}}
[2020-04-18 00:05:42,598]{/home/andrenovado/Documents/Coding/Alterra/fullstack5_andre_novado/Restful-API/Flask_routing/blueprints/__init__.py:60} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/rent/1?", "request": {"user_id": 1, "book_id": 1}, "response": {"id": 1, "book_id": 6, "user_id": "8", "return_date": "Fri, 17 Apr 2020 23:27:39 -0000", "created_at": "Fri, 17 Apr 2020 23:27:39 -0000", "updated_at": null, "deleted_at": null}}
