[2020-04-18 04:18:02,939]{/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /client/1 [GET]
Traceback (most recent call last):
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'client.deleted_at' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta14/Documents/Flask_routingbaru/blueprints/__init__.py", line 28, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta14/Documents/Flask_routingbaru/blueprints/client/resources.py", line 87, in get
    qry = Clients.query.get(id)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1004, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1121, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 287, in load_on_pk_identity
    return q.one()
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3360, in one
    ret = self.one_or_none()
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3329, in one_or_none
    ret = list(self)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3405, in __iter__
    return self._execute_and_instances(context)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/alta14/VirtualEnv/rest_training/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'client.deleted_at' in 'field list'")
[SQL: SELECT client.id AS client_id, client.client_key AS client_client_key, client.client_secret AS client_client_secret, client.salt AS client_salt, client.status AS client_status, client.address AS client_address, client.created_at AS client_created_at, client.updated_at AS client_updated_at, client.deleted_at AS client_deleted_at 
FROM client 
WHERE client.id = %(param_1)s]
[parameters: {'param_1': '1'}]
(Background on this error at: http://sqlalche.me/e/2j85)
[2020-04-18 04:18:02,949]{/home/alta14/Documents/Flask_routingbaru/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/client/1?", "request": {}, "response": {"message": "Internal Server Error"}}
[2020-04-18 04:18:52,656]{/home/alta14/Documents/Flask_routingbaru/blueprints/__init__.py:70} ERROR - REQUEST_LOG	{"method": "POST", "code": "400 BAD REQUEST", "uri": "/client?", "request": {"name": "Rosxxx", "age": 23, "sex": "Female", "client_id": 8}, "response": {"message": {"client_key": "Missing required parameter in the JSON body"}}}
[2020-04-18 04:20:24,504]{/home/alta14/Documents/Flask_routingbaru/blueprints/__init__.py:60} WARNING - REQUEST_LOG	{"method": "POST", "code": "200 OK", "uri": "/user?", "request": {"name": "Rosxxx", "age": 23, "sex": "Female", "client_id": 8}, "response": {"created_at": "Sat, 18 Apr 2020 04:20:24 -0000", "updated_at": null, "deleted_at": null, "id": 2, "name": "Rosxxx", "age": 23, "sex": "Female", "client_id": 8}}
[2020-04-18 04:20:49,077]{/home/alta14/Documents/Flask_routingbaru/blueprints/__init__.py:60} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/user?", "request": {}, "response": [{"created_at": "Fri, 17 Apr 2020 22:33:31 -0000", "updated_at": null, "deleted_at": null, "id": 1, "name": "Ros", "age": 23, "sex": "Female", "client_id": 0}, {"created_at": "Sat, 18 Apr 2020 04:20:24 -0000", "updated_at": null, "deleted_at": null, "id": 2, "name": "Rosxxx", "age": 23, "sex": "Female", "client_id": 8}]}
